apiVersion: apps/v1
kind: Deployment
metadata:
  name: webcrawler-deployment
  namespace: crawler
  labels:
    app: webcrawler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webcrawler
  template:
    metadata:
      labels:
        app: webcrawler
    spec:
      containers:
        - name: webcrawler
          image: docker.io/lokesh8130/webcrawler:v5
          env:
            - name: DBSERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: webcrawler-config
                  key: dbserver_url
            - name: DBSERVER_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: webcrawler-config
                  key: mysql_username
            - name: DBSERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: webcrawler-secret
                  key: mysql_root_password
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: webcrawler-service
  namespace: crawler
spec:
  type: NodePort
  selector:
    app: webcrawler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080