apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbserver-deployment
  namespace: crawler
  labels:
    app: dbserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbserver
  template:
    metadata:
      labels:
        app: dbserver
    spec:
      containers:
        - name: dbserver
          image: mysql:5.6
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dbserver-secret
                  key: mysql_root_password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: dbserver-config
                  key: mysql_database
          ports:
            - containerPort: 3306

---

apiVersion: v1
kind: Service
metadata:
  name: dbserver-service
  namespace: crawler
spec:
  type: NodePort
  selector:
    app: dbserver
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306